### ISSUE TITLE
Exception: Could not initialize the problem

### ISSUE THREAD

**Issue by HygorCosta** [OPM/opm-common#1397]
Hello guys,

I try to run a toy example, but this message appears:
```
Program threw an exception: Could not initialize the problem.
```
In .DBG file no error is show, only this brief table:
```
Error summary:
Warnings          0
Info                 59
Errors              0
Bugs                0
Debug              0
Problems         0
```
The data file is below.
[ToyReservoir.txt](https://github.com/OPM/opm-common/files/4035232/ToyReservoir.txt)

**Comment by joakim-hove** [comment]
This is the traceback:
```
(gdb) bt
#0  0x00007ffff4fe9afd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555574ce8ce in Opm::LiveOilPvt<double>::initFromDeck (this=0x555559e780a0, deck=..., eclState=...)
    at /home/hove/work/OPM2/opm-material/opm/material/fluidsystems/blackoilpvt/LiveOilPvt.hpp:188
#2  0x00005555574878e5 in Opm::OilPvtMultiplexer<double, true>::initFromDeck (this=0x555559f4c090, deck=..., eclState=...)
    at /home/hove/work/OPM2/opm-material/opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.hpp:150
#3  0x000055555744b9ec in Opm::BlackOilFluidSystem<double, Opm::BlackOilDefaultIndexTraits>::initFromDeck (deck=..., eclState=...)
    at /home/hove/work/OPM2/opm-material/opm/material/fluidsystems/BlackOilFluidSystem.hpp:223
#4  0x000055555741c2e9 in Opm::EclProblem<Opm::Properties::TTag::EclFlowProblem>::initFluidSystem_ (this=0x555559e07230) at /home/hove/work/OPM2/opm-simulators/ebos/eclproblem.hh:2454
#5  0x00005555573ebecd in Opm::EclProblem<Opm::Properties::TTag::EclFlowProblem>::finishInit (this=0x555559e07230) at /home/hove/work/OPM2/opm-simulators/ebos/eclproblem.hh:677
#6  0x00005555573d7b25 in Opm::Simulator<Opm::Properties::TTag::EclFlowProblem>::Simulator (this=0x555559df0d60, verbose=false) at /home/hove/work/OPM2/opm-models/opm/models/utils/simulator.hh:201
#7  0x00005555573c0786 in Opm::FlowMainEbos<Opm::Properties::TTag::EclFlowProblem>::setupEbosSimulator (this=0x7fffffffb490, output_cout=true)
    at /home/hove/work/OPM2/opm-simulators/opm/simulators/flow/FlowMainEbos.hpp:389
#8  0x00005555573b309c in Opm::FlowMainEbos<Opm::Properties::TTag::EclFlowProblem>::execute (this=0x7fffffffb490, argc=2, argv=0x7fffffffe178, output_cout=true, output_to_files=true)
    at /home/hove/work/OPM2/opm-simulators/opm/simulators/flow/FlowMainEbos.hpp:256
#9  0x000055555735a57a in Opm::flowEbosBlackoilMain (argc=2, argv=0x7fffffffe178, outputCout=true, outputFiles=true) at /home/hove/work/OPM2/opm-simulators/flow/flow_ebos_blackoil.cpp:63
#10 0x0000555557245f99 in main (argc=2, argv=0x7fffffffe178) at /home/hove/work/OPM2/opm-simulators/flow/flow.cpp:435
```
i.e. the crash comes while initializing the `PVTO` table - so I would look there.

**Comment by bska** [comment]
> the crash comes while initializing the `PVTO` table - so I would look there.

Here's an excerpt of the table (first and last records only)
```
PVTO
-- Tabela PVT para o  live oleo (gas and oil phases)
-- coluna 1: razao de solubilidade do gas no oleo 
-- coluna 2: pressao (barsa)
-- coluna 3: Fator volume formacao do oleo (rm3/sm3)
-- coluna 4: viscosidade do oleo (cP)
--    Rs          Psat         Bo         VisO        
--   (sm3/sm3)   (barsa)     (rm3/sm3)    (cP)       
       0.5 		   1.0130       1.074   	5.812680  /
-- [ ... Other entries omitted ... ]
     145.7 		 333.4261       1.445   	0.824782  / 
     177.1 		 392.2660       1.535   	0.715284  /
     /
```

Just from a quick glance, the PVTO table does not have undersaturated states for the maximum value of RS.  That's a problem in the input, and should be corrected there.

On the other hand, Flow should nevertheless be able to detect the missing entries and shut down gracefully.

**Comment by HygorCosta** [comment]
Thank you a lot guys! Sorry for the dumb question.
