### ISSUE TITLE
ImportError: libopmcommon.so.2022.04: cannot open shared object file

### ISSUE THREAD

**Issue by hakonhagland** [OPM/opm-common#2843]
When running a Python script using the shared libraries generated in the build folder (not in the install folder). The linker cannot find  `libopmcommon.so.2022.04`:

```
$ git clone git@github.com:OPM/opm-common.git
$ cd opm-common
$ mkdir build
$ cd build
$ cmake -DOPM_ENABLE_PYTHON=ON -DBUILD_SHARED_LIBS=ON ..
$ make -j12
```
Create  a test script `mytest.py` in the `python` folder:
```
$ cd python 
$ cat mytest.py
from opm.io.parser import Builtin
from opm.io.parser import Parser
from opm.io.parser import ParseContext
from opm.io.deck import DeckKeyword

parser = Parser()
data = """
START
10 MAI 2007 /
RUNSPEC
FIELD
DIMENS
2 2 1 /
GRID
DX
4*0.25 /
DY
4*0.25 /
DZ
4*0.25 /
"""
deck = parser.parse_string(data)
active_unit_system = deck.active_unit_system()
default_unit_system = deck.default_unit_system()
kw = DeckKeyword(
    parser["AQUCWFAC"], [["*", 0.25]], active_unit_system, default_unit_system)
```
Running this script generates the error:
```
$ python3 mytest.py
Traceback (most recent call last):
  File "/home/hakon/test/opm3/opm-common/build/python/mytest.py", line 1, in <module>
    from opm.io.parser import Builtin
  File "/home/hakon/test/opm3/opm-common/build/python/opm/io/__init__.py", line 1, in <module>
    from .parser import *
  File "/home/hakon/test/opm3/opm-common/build/python/opm/io/parser/__init__.py", line 1, in <module>
    from opm._common import action
  File "/home/hakon/test/opm3/opm-common/build/python/opm/_common.py", line 12, in <module>
    from .libopmcommon_python import action
ImportError: libopmcommon.so.2022.04: cannot open shared object file: No such file or directory
```
As mentioned in issue #2823, see https://github.com/OPM/opm-common/issues/2823#issuecomment-966565961 this could probably be fixed by adding an rpath to `libopmcommon.so.2022.04` when compiling `libopmcommon_python.cpython-39-x86_64-linux-gnu.so`. I plan to add a PR with a possible fix shortly.

**Comment by hakonhagland** [comment]
Added a possible fix, see #2844.

**Comment by blattms** [comment]
Closing as PR was merged
