### ISSUE TITLE
UDQParser::current() Accesses Vector out of Bounds

### ISSUE THREAD

**Issue by bska** [OPM/opm-common#682]
The implementation of [`UDQParser::current()`](https://github.com/OPM/opm-common/blob/a73e82110ceffb49254cbdee506eff3736222e2b/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp#L95-L96) contains the following code
```C++
const auto * token_ptr = std::addressof(this->tokens[this->current_pos + 1]);
```
This accesses the `tokens` array out of bounds if `this->current_pos == this->tokens.size() - 1`.  That definitely happens in the `UDQ_DEFINETEST` of [`UDQTests.cpp`](https://github.com/OPM/opm-common/blob/a73e82110ceffb49254cbdee506eff3736222e2b/tests/parser/UDQTests.cpp#L120) (GDB backtrace below), but I don't know if it happens in a real simulation run.  Here's the error I get when running the unit test in libstdc++'s debug mode:
```
/usr/include/c++/4.9/debug/vector:364:
Error: attempt to subscript container with out-of-bounds index 1, but 
container only holds 1 elements.

Objects involved in the operation:
    sequence "this" @ 0x0xdb9240 {
      type = ����;
    }

Program received signal SIGABRT, Aborted.
```

---

```
(gdb) bt
#0  0x00007ffff5cb1c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5cb5028 in __GI_abort () at abort.c:89
#2  0x00007ffff65ca6f3 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000000000977fef in std::__debug::vector<std::string, std::allocator<std::string> >::operator[] (this=0x7fffffff6228, __n=1) at /usr/include/c++/4.9/debug/vector:364
#4  0x0000000000d89f6d in Opm::UDQParser::current (this=0x7fffffff3a90) at /home/bska/work/opm/src/opm/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp:96
#5  0x0000000000d89e7e in Opm::UDQParser::next (this=0x7fffffff3a90) at /home/bska/work/opm/src/opm/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp:82
#6  0x0000000000d8acda in Opm::UDQParser::parse (udq_params=..., tokens=std::__debug::vector of length 1, capacity 1 = {...}, parseContext=..., errors=...)
    at /home/bska/work/opm/src/opm/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp:238
#7  0x0000000000b03522 in Opm::UDQDefine::UDQDefine (this=0x7fffffff6e40, udq_params=..., Python Exception <class 'gdb.error'> No type named class std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep.: 
keyword=, deck_data=std::__debug::vector of length 1, capacity 1 = {...}, parseContext=..., errors=...)
    at /home/bska/work/opm/src/opm/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp:124
#8  0x0000000000b0416c in Opm::UDQDefine::UDQDefine<Opm::ErrorGuard> (this=0x7fffffff6e40, udq_params=..., Python Exception <class 'gdb.error'> No type named class std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep.: 
keyword=, deck_data=std::__debug::vector of length 1, capacity 1 = {...}, parseContext=..., errors=...)
    at /home/bska/work/opm/src/opm/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp:70
#9  0x0000000000b02aef in Opm::UDQDefine::UDQDefine (this=0x7fffffff6e40, udq_params=..., Python Exception <class 'gdb.error'> No type named class std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep.: 
keyword=, deck_data=std::__debug::vector of length 1, capacity 1 = {...})
    at /home/bska/work/opm/src/opm/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp:77
#10 0x000000000091e769 in UDQ_DEFINETEST::test_method (this=0x7fffffffc01e) at /home/bska/work/opm/src/opm/opm-common/tests/parser/UDQTests.cpp:120
#11 0x000000000091e514 in UDQ_DEFINETEST_invoker () at /home/bska/work/opm/src/opm/opm-common/tests/parser/UDQTests.cpp:116
#12 0x0000000000954950 in boost::detail::function::void_function_invoker0<void (*)(), void>::invoke (function_ptr=...) at /data/projects/opm/inst/boost/1.63.0/include/boost-1_63/boost/function/function_template.hpp:118
#13 0x00007ffff6c3cef2 in boost::function0<void>::operator() (this=0x11caca8) at ./boost/function/function_template.hpp:771
#14 0x00007ffff6c3c72d in boost::detail::forward::operator() (this=0x7fffffffcee8) at ./boost/test/impl/execution_monitor.ipp:1300
#15 0x00007ffff6c3d308 in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke (function_obj_ptr=...) at ./boost/function/function_template.hpp:138
#16 0x00007ffff6c3d0b2 in boost::function0<int>::operator() (this=0x7fffffffcee0) at ./boost/function/function_template.hpp:771
#17 0x00007ffff6c3c9f9 in boost::detail::do_invoke<boost::shared_ptr<boost::detail::translator_holder_base>, boost::function<int ()> >(boost::shared_ptr<boost::detail::translator_holder_base> const&, boost::function<int ()> const&) (
    tr=..., F=...) at ./boost/test/impl/execution_monitor.ipp:281
#18 0x00007ffff6c3b2f4 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) (this=0x7ffff6f5d060 <boost::unit_test::singleton<boost::unit_test::unit_test_monitor_t>::instance()::the_inst>, F=...)
    at ./boost/test/impl/execution_monitor.ipp:864
#19 0x00007ffff6c3b459 in boost::execution_monitor::execute(boost::function<int ()> const&) (this=0x7ffff6f5d060 <boost::unit_test::singleton<boost::unit_test::unit_test_monitor_t>::instance()::the_inst>, F=...)
    at ./boost/test/impl/execution_monitor.ipp:1203
#20 0x00007ffff6c3c128 in boost::execution_monitor::vexecute(boost::function<void ()> const&) (this=0x7ffff6f5d060 <boost::unit_test::singleton<boost::unit_test::unit_test_monitor_t>::instance()::the_inst>, F=...)
    at ./boost/test/impl/execution_monitor.ipp:1309
#21 0x00007ffff6c8db29 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (
    this=0x7ffff6f5d060 <boost::unit_test::singleton<boost::unit_test::unit_test_monitor_t>::instance()::the_inst>, func=..., timeout=0) at ./boost/test/impl/unit_test_monitor.ipp:46
#22 0x00007ffff6c47f10 in boost::unit_test::framework::state::execute_test_tree (this=0x7ffff6f5ce40 <boost::unit_test::framework::impl::(anonymous namespace)::s_frk_state()::the_inst>, tu_id=65539, timeout=0, p_random_generator=0x0)
    at ./boost/test/impl/framework.ipp:717
#23 0x00007ffff6c477bd in boost::unit_test::framework::state::execute_test_tree (this=0x7ffff6f5ce40 <boost::unit_test::framework::impl::(anonymous namespace)::s_frk_state()::the_inst>, tu_id=1, timeout=0, p_random_generator=0x0)
    at ./boost/test/impl/framework.ipp:666
#24 0x00007ffff6c414fb in boost::unit_test::framework::run (id=1, continue_test=true) at ./boost/test/impl/framework.ipp:1442
#25 0x00007ffff6c89aa3 in boost::unit_test::unit_test_main (init_func=0x91ac42 <init_unit_test()>, argc=2, argv=0x7fffffffdf88) at ./boost/test/impl/unit_test_main.ipp:231
#26 0x000000000091acdd in main (argc=2, argv=0x7fffffffdf88) at /data/projects/opm/inst/boost/1.63.0/include/boost-1_63/boost/test/unit_test.hpp:63
```

**Comment by joakim-hove** [comment]
Thanks - that is definitely a bug.
